title: <p align="center"> Ganesh Visweswaran </p>
logo: /assets/img/GV.png
description:
  <p align="center">
  <a href="docs/GV_resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ganeshvisweswaran/">LinkedIn</a> |
  <a href="https://github.com/ganesh-hariraj">GitHub</a>
    <br>   
  16+ Years of techno functional experience in Credit risk Reporting, Commercial Banking 
  and IT Operations Domain playing roles across Risk Analytics, governance, 
  Data Analytics, Project Management and Automation
  <br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
