title: <p align="center"> Ganesh Visweswaran </p>
logo: /assets/img/GV.png
description:
  <p align="center">
  <a href="docs/GV_resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ganeshvisweswaran/">LinkedIn</a> |
  <a href="https://github.com/ganesh-hariraj">GitHub</a>


theme: jekyll-theme-minimal
