title: <p align="center"> Ganesh Visweswaran </p>
logo: /assets/img/GV.png
description: Data Science Portfolio of Ganesh Visweswaran
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
